
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action ConnectionAction;
	private global::Gtk.Action newAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action saveAsAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action connectAction;
	private global::Gtk.Action jumpToAction;
	private global::Gtk.Action disconnectAction;
	private global::Gtk.VBox vbox4;
	private global::Gtk.MenuBar menubar6;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.Label label5;
	private global::Gtk.Label labelStatus;
	private global::Gtk.Label label8;
	private global::Gtk.Label labelEqualizer;
	private global::Gtk.Label label10;
	private global::Gtk.Label labelEcho;
	private global::Gtk.Statusbar statusbar2;
	private global::Gtk.ProgressBar progressbar;
	private global::Gtk.Label statusLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ConnectionAction = new global::Gtk.Action ("ConnectionAction", global::Mono.Unix.Catalog.GetString ("Connection"), null, null);
		this.ConnectionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Connection");
		w1.Add (this.ConnectionAction, null);
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("_New"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
		w1.Add (this.saveAsAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.connectAction = new global::Gtk.Action ("connectAction", global::Mono.Unix.Catalog.GetString ("C_onnect"), null, "gtk-connect");
		this.connectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("C_onnect");
		w1.Add (this.connectAction, null);
		this.jumpToAction = new global::Gtk.Action ("jumpToAction", global::Mono.Unix.Catalog.GetString ("Program"), null, "gtk-jump-to");
		this.jumpToAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Program");
		w1.Add (this.jumpToAction, null);
		this.disconnectAction = new global::Gtk.Action ("disconnectAction", global::Mono.Unix.Catalog.GetString ("_Disconnect"), null, "gtk-disconnect");
		this.disconnectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Disconnect");
		w1.Add (this.disconnectAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar6'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='ConnectionAction' action='ConnectionAction'><menuitem name='connectAction' action='connectAction'/><menuitem name='jumpToAction' action='jumpToAction'/><menuitem name='disconnectAction' action='disconnectAction'/></menu></menubar></ui>");
		this.menubar6 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar6")));
		this.menubar6.Name = "menubar6";
		this.vbox4.Add (this.menubar6);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.menubar6]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Status");
		this.notebook1.Add (this.label5);
		// Notebook tab
		this.labelStatus = new global::Gtk.Label ();
		this.labelStatus.Name = "labelStatus";
		this.labelStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("Status");
		this.notebook1.SetTabLabel (this.label5, this.labelStatus);
		this.labelStatus.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Equalizer");
		this.notebook1.Add (this.label8);
		global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.label8]));
		w4.Position = 1;
		// Notebook tab
		this.labelEqualizer = new global::Gtk.Label ();
		this.labelEqualizer.Name = "labelEqualizer";
		this.labelEqualizer.LabelProp = global::Mono.Unix.Catalog.GetString ("Equalizer");
		this.notebook1.SetTabLabel (this.label8, this.labelEqualizer);
		this.labelEqualizer.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Echo");
		this.notebook1.Add (this.label10);
		global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.label10]));
		w5.Position = 2;
		// Notebook tab
		this.labelEcho = new global::Gtk.Label ();
		this.labelEcho.Name = "labelEcho";
		this.labelEcho.LabelProp = global::Mono.Unix.Catalog.GetString ("Echo");
		this.notebook1.SetTabLabel (this.label10, this.labelEcho);
		this.labelEcho.ShowAll ();
		this.vbox4.Add (this.notebook1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.notebook1]));
		w6.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.statusbar2 = new global::Gtk.Statusbar ();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 6;
		// Container child statusbar2.Gtk.Box+BoxChild
		this.progressbar = new global::Gtk.ProgressBar ();
		this.progressbar.Name = "progressbar";
		this.progressbar.Text = "";
		this.progressbar.PulseStep = 0.06D;
		this.statusbar2.Add (this.progressbar);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.statusbar2 [this.progressbar]));
		w7.Position = 1;
		// Container child statusbar2.Gtk.Box+BoxChild
		this.statusLabel = new global::Gtk.Label ();
		this.statusLabel.WidthRequest = 150;
		this.statusLabel.Name = "statusLabel";
		this.statusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Not connected");
		this.statusbar2.Add (this.statusLabel);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.statusbar2 [this.statusLabel]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox4.Add (this.statusbar2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.statusbar2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(2));
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 818;
		this.DefaultHeight = 540;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.connectAction.Activated += new global::System.EventHandler (this.Connect);
		this.disconnectAction.Activated += new global::System.EventHandler (this.Disconnect);
	}
}
